version: "3.6"
services: 
    jupyter: 
        image: jupyter/base-notebook
        ports: 8890:8888
    nginx: 
        images: nginx
        volumes: 
            - ./data/nginx/nginx.conf:/etc/nginx.conf
            - ./data/nginx/conf.d:/etc/conf.d
        ports: 
             - "80:80"
             - “443：443”
        depends-on: 
            - jupyter
    certbot: 
        images: certbot/certbot
        volumes: 
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
              -
